### ISSUE TITLE
Invalid Version Range in mods.toml

### ISSUE THREAD

**Issue by VaiN474** [nanite/JAMD#1]
### Mod version

forge-2.0.3-build.10+mc1.19.2

### Forge mod loader version

43.1.43

### Repeatable?

- [ ] Yes

### Link to log files

didn't save them, sry

### Description of the issue you are having

sry for lack of logs, but it's a simple issue

mods.toml has invalid minecraft version range causing forge to crash instantly with "InvalidVersionSpecificationException" error.

```
versionRange = "[1.19.2)"
```

fix:

```
versionRange = "[1.19.2,)"
```

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
It building now should on curseforge soon
