### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by itsdinkd** [nanite/JAMD#10]
### Minecraft Version

1.19.2

### Modloader

Fabric 0.14.12

### Mod version

2.0.5 build 12

### Repeatable?

- [ ] Yes

### Link to log files

https://gist.github.com/itsdinkd/133336e01366d8d1a087b2de7529f3dd

HD java crash report https://gist.github.com/itsdinkd/e6b5beeb11e323f369f7902cd262c2ec

### Steps to reproduce the issue

1. Place down teleporter
2. teleport to Mining Dim
3. Teleport back
4. crash

### Description of the issue you are having

Logs gave no indication of crash, no errors, no crash report either. It did however generate a java crash report. https://gist.github.com/itsdinkd/e6b5beeb11e323f369f7902cd262c2ec 

Teleporting back crashed game. plain and simple

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Please remove terrablender and see if it still happens
