### ISSUE TITLE
Datapack help to add mod ore

### ISSUE THREAD

**Issue by penturt** [nanite/JAMD#12]
### Minecraft Version

1.19.2

### Modloader

forge-1.19.2 - 43.2.8

### Mod version

jamd-forge-2.0.5-build.12+mc1.19.2

### Repeatable?

- [ ] Yes

### Link to log files

N/A

### Description of the issue you are having

I'm trying to get mekanism, gobber, and powah ores to generate in the JAMD mining dimension. I see its mentioned a datapack is needed, where can i find a sample or format needed for said datapack, and what is the required folder structure and location to place datapack? I've looked around the GitHub but have not been able to find anything, maybe I'm looking in the wrong locations, but I even followed an old post i found and didn't see any instructions.

 thank you in advance, and sorry I haven't worked with creating datapacks before so this is new to me.

### Information

- [X] I have provided as much information as possible

**Comment by llloyd4** [comment]
Same here, let me know when you find out, or make a Youtube video for dummies ? >.< Thanks.

**Comment by ViperSlayer9869** [comment]
I need to know this too. I have looked around but I can't find any instructions.

**Comment by Shybella** [comment]
I don't understand why this mod exists, plenty of flat world generators out there but somehow you can rebrand them as mining dimensions.

**Comment by UnRealDinnerbone** [comment]
For 1.19 the datapack contests of file located 
in https://github.com/nanite/JAMD/tree/1.19.3/common/src/main/resources/data/jamd/dimension
and https://github.com/nanite/JAMD/tree/1.19.3/forge/src/generated/resources/data/jamd 

How Datapack Works https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

For Changing custom ore gen you would make a datapack the overrides my biome and adds the custom ores features you want


You can also mods like KubeJS to change the ore gen
