### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Zonk1987** [nanite/JAMD#14]
### Minecraft Version

1.19.2

### Modloader

forge-1.19.2-43.2.8

### Mod version

jamd-forge-2.0.5-build.12+mc1.19.2

### Repeatable?

- [X] Yes

### Link to log files

there are nothing to see in the logs

### Steps to reproduce the issue

1. Put on the Gobber 2 Full set Dragon Armor
2. Go to the dimension
3. leave the game 
4. join back in the game
5. and now you can not fly anymore

### Description of the issue you are having

Modpack: Direwolf 20 1.19 Version 1.9.0

the issue is described in the steps above.

If you are going back in the overworld and back in the mining dim than you can fly as normaly.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Not me issue, mod needs to handle dimension teleporting
