### ISSUE TITLE
Creating datapacks for this mod

### ISSUE THREAD

**Issue by ghost** [nanite/JAMD#16]
So, i read all the closed issues about datapacks, but i didn't understand what am i suposed to write in the mining.json file, what should i edit in it, author please make a example datapack, as you said it exist in the Curseforge page.

**Comment by UnRealDinnerbone** [comment]
For 1.19 the datapack contests of file located
in https://github.com/nanite/JAMD/tree/1.19.3/common/src/main/resources/data/jamd/dimension
and https://github.com/nanite/JAMD/tree/1.19.3/forge/src/generated/resources/data/jamd

For 1.20
https://github.com/nanite/JAMD/tree/1.20.1/Common/src/generated/resources/data/jamd

How Datapack Works https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

For Changing custom ore gen you would make a datapack the overrides my biome and adds the custom ores features you want

You can also mods like KubeJS to change the ore gen

**Comment by ghost** [comment]
And what i am supposed to do with these links? I don't know how to make a datapack or what add to the mining.json file that lets it generates modded ores.
