### ISSUE TITLE
Is this compatible with the Immersive portals mod?

### ISSUE THREAD

**Issue by ChaoticUltimateJ** [nanite/JAMD#17]
If not, is there any compatibility planned in the future?

**Comment by ChaoticUltimateJ** [comment]
I don't know how to add the question label

**Comment by UnRealDinnerbone** [comment]
If Immersive Portals supports other dimensions, then yes. I'm not doing anything special

**Comment by ChaoticUltimateJ** [comment]
I see. Thank you.
