### ISSUE TITLE
[Issue] Conflict between JAMD-1.7.0-build.25+mc1.18.2 and Terrablender Forge 1.18.2-1.2.0.126

### ISSUE THREAD

**Issue by Rensik** [nanite/JAMD#2]
### Mod version

JAMD-1.7.0-build.25+mc1.18.2

### Forge mod loader version

40.1.84

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/JAMD/files/9840991/latest.log)

### Steps to reproduce the issue

Have both mods installed.
Visit JAMD's dimension.
Strip stone and deep slate away to reveal any other terrain generation via World Stripper or MC Commands, or however you wish to do it.
See no other terrain generation.

### Description of the issue you are having

Terrablender Forge 1.18.2-1.2.0.126(currently most recent as of this posting) causes JAMD's Mining Dimension to be completely void of all other terrain gen besides Grass, Dirt, Stone, Deepslate and Bedrock. The "fix" is to use Terrablender Forge 1.18.2-1.1.0.102.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
This is Terrabelender issue https://github.com/Glitchfiend/TerraBlender/issues/94
