### ISSUE TITLE
when loading into the dim i crash[Issue]

### ISSUE THREAD

**Issue by geterhun** [nanite/JAMD#22]
### Minecraft Version

1.20.1

### Modloader

forge 47.2.0

### Mod version

3.3.3

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

https://mclo.gs/KJB1xZw

### Steps to reproduce the issue

1.) make any mining portal 
2.)place and right click on the portal

### Description of the issue you are having

i just crash when right clicking on the portal here is my modpack too is what im using on my server

[https://legacy.curseforge.com/minecraft/modpacks/mysticmodpackunleashed/files](url)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Same as #21
