### ISSUE TITLE
[Question] Generate blocks from other dimensions

### ISSUE THREAD

**Issue by penturt** [nanite/JAMD#26]
### Feature Description

Is it possible generate blocks from other dimensions, example blocks from the End, Nether? I've tried using a datapack but have had no luck, not sure if i'm doing something wrong.

**Comment by UnRealDinnerbone** [comment]
Starting in the 1.20+ versions there end and nether mining dims, unless you mean for another version?

**Comment by penturt** [comment]
how to you get to the other dims?

**Comment by UnRealDinnerbone** [comment]
make the portal block? they have recipes

**Comment by penturt** [comment]
Yeah ignore me, I opened the wrong instances from the luncher. Thank you

**Comment by penturt** [comment]
did something change in the format for the datapack? or rather do datapacks still work to add ores from other mods into the mining world?

In 1.19 i used this datapack to generate some powah and mek ore in the mining world, but its not working in 1.20.1 for me.

**Using:** 
Forge 1.20.1 - 47.2.20
JAMD Forge 3.4.2+mc1.20.1

**Datapack location:**
...\data\jamd\worldgen\biome\mining.json

**mining.json file:** https://pastebin.com/RuPEYChs

**Comment by UnRealDinnerbone** [comment]
You now add them in the config file config/jamd/type.json

**Comment by penturt** [comment]
Alright thank you
