### ISSUE TITLE
[Issue] Duplicate stacked portal when leaving mining dimension

### ISSUE THREAD

**Issue by MacChuck** [nanite/JAMD#28]
### Minecraft Version

1.20.1

### Modloader

neoforge 47.1.85

### Mod version

jamd-forge-3.4.2+mc1.20.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

latest.log: https://mclo.gs/Qug7qUi

### Description of the issue you are having

Entering and leaving the mining dimension causes another copy of the portal to spawn nearby, usually a few blocks above the exiting one. I tried a clean install with only JAMD and Trenzalore with no other mods.

![image](https://github.com/nanite/JAMD/assets/16522925/e3e154d9-3d25-4aeb-8e6d-847d23ea8019)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Looked into this it a minecraft bug when setting blocks and changing dimensions
