### ISSUE TITLE
Example Datapacks and Mod Ores[Issue]

### ISSUE THREAD

**Issue by JustLutz** [nanite/JAMD#3]
### Mod version

mc.1.16.5

### Repeatable?

- [x] Yes

### Link to log files

no Link

### Description of the issue you are having

Hi, where are the example Datapacks and does the world have ores from other mods like Mekanism?

### Information

- [x] I have provided as much information as possible

**Comment by xR4YM0ND** [comment]
yep we need documentation ... 

what about mod compat in datapacks?

and may some pictures on your curseforge page

**Comment by Akzyra** [comment]
This is what I gathered checking the files in the repo:

- mining dimension is a customizable flat world 
- overworld ore generation, with extra emeralds (like mountain biomes?)
- extra tuff generation

For editing the dimension create a datapack with the file `data/jamd/dimension/mining.json`.
Default settings are [here](https://github.com/nanite/JAMD/blob/master/common/src/main/resources/data/jamd/dimension/mining.json).

@UnRealDinnerbone Please add some information like this to the README or a GItHub Wiki or something.
I hope I got everything important, but I have no idea about world gen, please correct me if I am worng.
