### ISSUE TITLE
[Feature Request] Daylight Cycle

### ISSUE THREAD

**Issue by andr9528** [nanite/JAMD#30]
### Feature Description

The game has a gamerule to decide if daylight cycles or not.
Would be neat if this mod either followed that, or better yet, had its own similar gamerule, as to remain independent from overworld time passing.

Would make the dimentions one step closer to livable, if one want to do so.
Should of course default to as it right now, i.e time frozen.

**Comment by UnRealDinnerbone** [comment]
You can change this by modifying the daylight values in https://github.com/nanite/JAMD/blob/1.20.1/common/src/generated/resources/data/jamd/dimension_type/mining.json with a datapack

**Comment by HalJordan** [comment]
This used to be a simple edit of the config file. Swapping to using datapacks for this is horribly convoluted. For changing the ore distribution, I sort of get, but a simple setting change like this???
