### ISSUE TITLE
How can I enable mob spawning in the mining dimension?

### ISSUE THREAD

**Issue by JoaoFernandes02** [nanite/JAMD#31]
I tried creating a datapack so I could change the light level (which I did successfully) but I can't enable mob spawning, what do I need to do?

To change the light level I just copy pasted the datapack example and changed ambient light to 0 (it was 1)

Minecraft version: 1.20.1

**Comment by UnRealDinnerbone** [comment]
You need to add the mobs in the spawners part of the biome json

**Comment by JoaoFernandes02** [comment]
Every single mob? Isnt there a way to simply use the same rules as overworld? As im using a modpack theres a lot of mobs

**Comment by UnRealDinnerbone** [comment]
Yes, even modded ones. And as overworld, they're not really Overworld spawns, as spawns are per biome, You could use KubeJS for example to copy the spawns from plans biome
