### ISSUE TITLE
[Feature Request] Can we please get a datapack example?

### ISSUE THREAD

**Issue by DevRustic** [nanite/JAMD#32]
### Feature Description

Please just make a simple readme on how to create a datapack. 

I added this to my modpack, but like 3 modded ores spawn. No uranium, no nothing like that. Add an example datapack that shows how to add more ores.

**Comment by Kieranwest** [comment]
+1

**Comment by Nicon4454** [comment]
Hello Can we please open the wiki section of the github so that someone who knows how to do this can write it up in the wiki.

**Comment by UnRealDinnerbone** [comment]
For versions 1.20.1+ you don't need to use a datapack. As the files are now in config/jamd/
Also provides are a config option to add multiply the amount of ores that spawn

**Comment by CrimsonFrost1** [comment]
> For versions 1.20.1+ you don't need to use a datapack. As the files are now in config/jamd/ Also provides are a config option to add multiply the amount of ores that spawn

If this is the case it would be a good idea to change the description on CurseForge because it still states the changes are made through datapacks. This is the first and *only* time I've seen it said that the mod doesn't use datapacks anymore for different ores.
