### ISSUE TITLE
[Issue] Not generating any ores in jamd, 1.21.1 neoforge 21.1.71

### ISSUE THREAD

**Issue by Erelaszun** [nanite/JAMD#36]
### Minecraft Version

1.21.1

### Modloader

Neoforge 21.1.71

### Mod version

Neo 5.1.0

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

Nothing in logs

### Steps to reproduce the issue

Install jamd, go to mining dimension, no ore generation at all

### Description of the issue you are having

It seems in 1.21.1, jamd has no generation at all. Even used an X-Ray mod to check as well. Just Grass, Dirt, Stone, Deepslate, and Bedrock... 

### Information

- [X] I have provided as much information as possible

**Comment by VoxelVixen** [comment]
At first i had the same problem in my modpack but with neoforge 21.1.72 on my server.
After some testing i could get vanilla ores to show but not the modded ores.

What does work is first making a SP world , let it generate the world ,  close it , delete the mining.json on the server (config/JAMD) , upload the mining.json of your SP world's JAMD folder to your server's JAMD folder.

The modded ores now show up when i check with worldstripper.

**Comment by Erelaszun** [comment]
So this is all in Singleplayer, I have not created a server for this pack I am making yet. but even with a generated mining.json file, nothing is spawning once you goto the mining dimension, just grass, dirt, stone, deepslate, and bedrock.

**Comment by Erelaszun** [comment]
[mining.json](https://github.com/user-attachments/files/17469122/mining.json)

**Comment by Erelaszun** [comment]
After just checking all my mods, I see where the conflict was.... Mind you, none of this was shown in the Logs... I just took a guess and got Lucky.

[https://www.curseforge.com/minecraft/mc-mods/mt-chunk-generation](url)

Does not work with JAMD. It was stopping the proper generation.
After I Removed MTChunkGeneration... JAMD started working properly
