### ISSUE TITLE
[Issue] Mining dimension empty of ores.

### ISSUE THREAD

**Issue by Moussasasdas** [nanite/JAMD#39]
### Minecraft Version

1.21.1

### Modloader

neoforge-21.1.84

### Mod version

5.1.0+mc1.21.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

hmm this ain't a crash but worse. no ores?

### Steps to reproduce the issue

1. open new world. 2. go to mining dimension. 3. dig down and xray just to find 0 ores in the vicinity.

### Description of the issue you are having

Mining dimension has no ores at all in my hardcore world.

### Information

- [X] I have provided as much information as possible

**Comment by wraith1910** [comment]
were you able to fix this issue im having the same problem on my craftoria server 1.21.1
