### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by 74kumi** [nanite/JAMD#4]
### Feature Description

Is there someway to have the jamd generate the world at build limit since there are now ores that spawn at the upper limits now?

**Comment by UnRealDinnerbone** [comment]
this can be done with a datapack and changing the values in data/jamd/dimension/mining.json

**Comment by 74kumi** [comment]
I apologize for opening a closed issue...  I guess i need more info on the datapacks, the info on curseforge says " Mining dimension is editable with datapacks. see Github page for example datapack" Where is the example datapack did i just miss it?
