### ISSUE TITLE
[Issue] Solar Panels Don't Work in Mining Dimension

### ISSUE THREAD

**Issue by EatsALot** [nanite/JAMD#6]
### Minecraft Version

1.16.5

### Modloader

forge-36.2.26

### Mod version

FTB Ultimate: Anniversary Edition 1.3.0

### Repeatable?

- [X] Yes

### Link to log files

No logs available?

### Steps to reproduce the issue

Place any solar Panel in the mining dimension.
Open up the solar panel, it doesn't produce any EV.
F3 says that there is no light from the sky even though it is always day.

### Description of the issue you are having

I believe there is an issue with the light in the world. Solar panels can't get energy because it says there is no light in the mining dimension.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
This is indeed use datapack to change it
