### ISSUE TITLE
[Issue] Modded (Forge) Minecraft wont load this mod

### ISSUE THREAD

**Issue by Nijoma69** [nanite/JAMD#8]
### Minecraft Version

1.19.3

### Modloader

forge-1.19.3-44.1.5

### Mod version

jamd-forge-2.1.0-build.13+mc1.19.3

### Repeatable?

- [X] Yes

### Link to log files

[crash-2023-01-21_17.37.25-fml.txt](https://github.com/nanite/JAMD/files/10472708/crash-2023-01-21_17.37.25-fml.txt)

### Description of the issue you are having

Hi UDB,

I have a modded (forge) Minecraft installation which wont load this mod, during loading Minecraft errors and displays: -

Mod jamd requires minecraft 1.19.2
Currently, minecraft is 1.19.3

Not entirely sure if this helps but I've noticed that the mods.toml shows: -

[[dependencies.jamd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

Regards

Nick

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
New version on curseforge should fix it
