### ISSUE TITLE
inability to craft

### ISSUE THREAD

**Issue by Rogenar** [nanite/JAMD#9]
### Minecraft Version

1.19.3

### Modloader

fabric 0.14.13

### Mod version

jamd-fabric-2.2.2

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/JAMD/files/10473111/latest.log)
[rei.log](https://github.com/nanite/JAMD/files/10473112/rei.log)
[rei-issues.log](https://github.com/nanite/JAMD/files/10473114/rei-issues.log)

### Description of the issue you are having

 Unable to make portal block in jamd-fabric-2.2.2. But it can only be retrieved by command.

![1](https://user-images.githubusercontent.com/122460325/213887808-3249f444-3ab7-4994-af1f-b0711103c30e.png)
![2](https://user-images.githubusercontent.com/122460325/213887811-e199b466-ed23-42f1-83a3-ad93cf311f18.png)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Fixed in latest commit
